[package]
name = "kibou"
version = "0.1.0"
authors = ["Toromino <foxhkron@toromino.de>"]

[dependencies]
base64 = "0.10.1"
chrono = "0.4"
config = "0.9.2"
diesel = { version = "1.0.0", features = ["chrono", "postgres", "serde_json"] }
openssl-sys = "0.9"
openssl = "0.10"
pem = "0.5.1"
regex = "1.1.2"
reqwest = "0.9.9"
rocket = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "1.7.2"
uuid = { version = "0.6", features = ["serde", "v4"] }

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json", "tera_templates"]
